### ISSUE TITLE
querySelector fallacy

### ISSUE THREAD

**Issue by dfcreative** [litejs/dom-lite#21]
Current querySelector implementation is fallacious due to wrong algorithm. To illustrate:

```js
//create test elements
var ul = document.createElement('ul')
var li = document.createElement('li')
ul.appendChild(li);

//simple selector
ul.querySelectorAll('ul li'); //⇒ [<li>], not [], as expected. Surprise!

//to illustrate why - it roughly works as follows:
document.querySelectoAll('ul li').filter(within(ul));
```

So the proper element's querySelector just filters all elements queried in the document, but not starts querying from itself, as it does `dom-lite`.

@lauriro @hayes

**Comment by dfcreative** [comment]
Woops, I haven’t event noticed that child selectors `div > span` neither work.

**Comment by lauriro** [comment]
Duplicate of #16
